---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: custom-nginx-app-deployment
  namespace: metallb
  labels:
    app: custom-nginx-app
spec:
  selector:
    matchLabels:
      app: custom-nginx-app
  template:
    metadata:
      labels:
        app: custom-nginx-app
    spec:
      containers:
        - name: custom-nginx-app
          image: ren1007/custom-nginx:1.2
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          resources:
            requests:
              memory: "512Mi"
              cpu: "1"
            limits:
              memory: "1Gi"
              cpu: "2"
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: custom-nginx-app-hpa
  namespace: metallb
  labels:
    app: custom-nginx-app
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: custom-nginx-app-deployment
  minReplicas: 1
  maxReplicas: 12
  metrics:
    - resource:
        name: cpu
        target:
          averageUtilization: 40
          type: Utilization
      type: Resource
  behavior:
    # 10s で最大1つのレプリカをスケールアップ
    scaleUp:
      stabilizationWindowSeconds: 0 # 即時スケールアップ
      policies:
        - type: Pods
          value: 1
          periodSeconds: 10
    # 10s で最大1つのレプリカをスケールダウン
    scaleDown:
      stabilizationWindowSeconds: 5 # 5s で必要レプリカ数まで削減
      policies:
        - type: Pods
          value: 1
          periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: custom-nginx-app-service
  namespace: metallb
spec:
  selector:
    app: custom-nginx-app
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer
  externalTrafficPolicy: Local
